// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class tbTransportistas
    {
        public tbTransportistas()
        {
            tbViajes = new HashSet<tbViajes>();
        }

        public int tran_Id { get; set; }
        public string tran_Nombres { get; set; }
        public string tran_Apellidos { get; set; }
        public string tran_Identidad { get; set; }
        public DateTime tran_FechaNacimiento { get; set; }
        public string tran_Sexo { get; set; }
        public int eciv_Id { get; set; }
        public string muni_Id { get; set; }
        public string tran_DireccionExacta { get; set; }
        public string tran_Telefono { get; set; }
        public decimal tran_PagoKm { get; set; }
        public int tran_UsuCreacion { get; set; }
        public DateTime tran_FechaCreacion { get; set; }
        public int? tran_UsuModificacion { get; set; }
        public DateTime? tran_FechaModificacion { get; set; }
        public bool? tran_Estado { get; set; }

        public virtual tbEstadosCiviles eciv { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios tran_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios tran_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbViajes> tbViajes { get; set; }
    }
}