// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseuser_UsuCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseuser_UsuModificacionNavigation = new HashSet<tbUsuarios>();
            tbColaboradoresPorSucursalcosu_UsuCreacionNavigation = new HashSet<tbColaboradoresPorSucursal>();
            tbColaboradoresPorSucursalcosu_UsuModificacionNavigation = new HashSet<tbColaboradoresPorSucursal>();
            tbColaboradorescola_UsuCreacionNavigation = new HashSet<tbColaboradores>();
            tbColaboradorescola_UsuModificacionNavigation = new HashSet<tbColaboradores>();
            tbDepartamentosdepa_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEstadosCivileseciv_UsuCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivileseciv_UsuModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbMunicipiosmuni_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasPorRolesprol_UsuCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesprol_UsuModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbRolesrole_UsuCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuModificacionNavigation = new HashSet<tbRoles>();
            tbSucursalessucu_UsuCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UsuModificacionNavigation = new HashSet<tbSucursales>();
            tbTransportistastran_UsuCreacionNavigation = new HashSet<tbTransportistas>();
            tbTransportistastran_UsuModificacionNavigation = new HashSet<tbTransportistas>();
            tbViajesDetallesvide_UsuCreacionNavigation = new HashSet<tbViajesDetalles>();
            tbViajesDetallesvide_UsuModificacionNavigation = new HashSet<tbViajesDetalles>();
            tbViajesviaj_UsuCreacionNavigation = new HashSet<tbViajes>();
            tbViajesviaj_UsuModificacionNavigation = new HashSet<tbViajes>();
        }

        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Contrasena { get; set; }
        public bool? user_EsAdmin { get; set; }
        public int? role_Id { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime user_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }

        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradoresPorSucursal> tbColaboradoresPorSucursalcosu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbColaboradoresPorSucursal> tbColaboradoresPorSucursalcosu_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradorescola_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradorescola_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivileseciv_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivileseciv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesprol_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesprol_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbTransportistas> tbTransportistastran_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbTransportistas> tbTransportistastran_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbViajesDetalles> tbViajesDetallesvide_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbViajesDetalles> tbViajesDetallesvide_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbViajes> tbViajesviaj_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbViajes> tbViajesviaj_UsuModificacionNavigation { get; set; }
    }
}