// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class tbViajes
    {
        public tbViajes()
        {
            tbViajesDetalles = new HashSet<tbViajesDetalles>();
        }

        public int viaj_Id { get; set; }
        public int tran_Id { get; set; }
        public int sucu_Id { get; set; }
        public DateTime viaj_FechaViaje { get; set; }
        public int viaj_UsuCreacion { get; set; }
        public DateTime viaj_FechaCreacion { get; set; }
        public int? viaj_UsuModificacion { get; set; }
        public DateTime? viaj_FechaModificacion { get; set; }
        public bool? viaj_Estado { get; set; }

        public virtual tbSucursales sucu { get; set; }
        public virtual tbTransportistas tran { get; set; }
        public virtual tbUsuarios viaj_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios viaj_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbViajesDetalles> tbViajesDetalles { get; set; }
    }
}