// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class tbViajesDetalles
    {
        public int vide_Id { get; set; }
        public int viaj_Id { get; set; }
        public int cola_Id { get; set; }
        public int vide_UsuCreacion { get; set; }
        public DateTime vide_FechaCreacion { get; set; }
        public int? vide_UsuModificacion { get; set; }
        public DateTime? vide_FechaModificacion { get; set; }
        public bool? vide_Estado { get; set; }

        public virtual tbColaboradores cola { get; set; }
        public virtual tbViajes viaj { get; set; }
        public virtual tbUsuarios vide_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios vide_UsuModificacionNavigation { get; set; }
    }
}