// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class VW_tbViajesDetalles
    {
        public int vide_Id { get; set; }
        public int viaj_Id { get; set; }
        public int cola_Id { get; set; }
        public string cola_NombreCompleto { get; set; }
        public string cola_Identidad { get; set; }
        public int vide_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime vide_FechaCreacion { get; set; }
        public int? vide_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? vide_FechaModificacion { get; set; }
        public bool vide_Estado { get; set; }
    }
}