// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class VW_tbViajes
    {
        public int viaj_Id { get; set; }
        public int tran_Id { get; set; }
        public string tran_NombreCompleto { get; set; }
        public int sucu_Id { get; set; }
        public string sucu_Nombre { get; set; }
        public DateTime viaj_FechaViaje { get; set; }
        public int viaj_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime viaj_FechaCreacion { get; set; }
        public int? viaj_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? viaj_FechaModificacion { get; set; }
        public bool viaj_Estado { get; set; }
    }
}