// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Viajes.Entities.Entities
{
    public partial class VW_tbTransportistas
    {
        public int tran_Id { get; set; }
        public string tran_Nombres { get; set; }
        public string tran_Apellidos { get; set; }
        public string tran_NombreCompleto { get; set; }
        public string tran_Identidad { get; set; }
        public DateTime tran_FechaNacimiento { get; set; }
        public string tran_Sexo { get; set; }
        public int eciv_Id { get; set; }
        public string eciv_Descripcion { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public string tran_DireccionExacta { get; set; }
        public string tran_Telefono { get; set; }
        public decimal tran_PagoKm { get; set; }
        public int tran_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime tran_FechaCreacion { get; set; }
        public int? tran_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? tran_FechaModificacion { get; set; }
        public bool tran_Estado { get; set; }
    }
}